#!/usr/bin/env bash
#
# bootstrap installs things.

source ./scripts/functions

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

#setup_gitconfig
install_dotfiles
install_submodules
info "Running scripts from ./install"
#Run other scripts
for src in $(find -H ./install -name '*.install')
do
  chmod +x $src
  ./$src
  name=$(basename $src)
  info "$name $res"
done

